services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker pull j0elwee/devops-trg
  - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from j0elwee/devops-trg -t j0elwee/devops-trg -t j0elwee/devops-trg:$TRAVIS_COMMIT --target production .
  - docker pull j0elwee/devops-trg:python-3.8-slim-buster-with-geckodriver
  - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from j0elwee/devops-trg:python-3.8-slim-buster-with-geckodriver -t j0elwee/devops-trg:python-3.8-slim-buster-with-geckodriver -f Dockerfile.test.base .
script:
  - docker-compose -f docker-compose.test.yml up --exit-code-from tests
before_deploy:
  - echo $DOCKER_HUB_PASSWORD | docker login -u j0elwee --password-stdin
  - docker push j0elwee/devops-trg
  - docker push j0elwee/devops-trg:$TRAVIS_COMMIT
  - docker push j0elwee/devops-trg:python-3.8-slim-buster-with-geckodriver
deploy:
  provider: script
  script: 'curl -dH -X POST "https://\$joel-devops:WTggTqMvjESp8WlxN2oA4XsomqrjlpR5G48n8bAQmmvp9JFnJ8rXbA31bLwB@joel-devops.scm.azurewebsites.net/docker/hook"'
  on: 
    branch: mod-11-azure
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.28.2
  - secure: UwMUyLZN1g+zqo+7+xIftHXzpWSKUWhS2DZHQSMdPURlD/n9GMZvuJXJ7mzh1MV1KJi+acIPE7Ho3pLVdu1zTkJ47oN8dsnLzXih6yaqD768b51/u0v/G49+9nsjUBkQ5ds7ZvC9OyW1uYKU1aUfjL9X3ejcbmUbfXTMLGPFPbRS/4S3a9HmgzYjFCPPEMZvwppufojhZ72HirjYISRk0KjB+KWcmqShpsZvef+H4VEdGTsdiWjhq3SaTU1R7FF5kcg4j3hN5guZFwIYfJMVG8RouCvzGU2voAbBNImu5Dugwna0cZJPZVJvz88vTimMKal8E22EC3aNaduB9pNcF9lWYmSwL/aoXCGfXke9swXRtSV4Ma+cpZYFb+ju/Af2WoOybs9ygTH5L5aV7wg3P5XuB1AkCPbr1uQsmQbENvDqJNU8hhDmezYXhr4jLOtZ8DF37jtMDhUAeFhQpKZMcxaay5cvaupEUILI1QaFWSmcYgXWz0yonR0gooXZHfZYJZZ98nFqOGGsLgrz/M0DVN6EBBRqNXjKW8RtTzHXRDe2EuPu2r7UrLbE1upTAHwc9xtAWxVorTxkpZvFA9bml0HGjS8ak2yRfVxrDC/Xm5wGPsNBLkRh73h2H5UjOjEyRiumPOKM/JrEwysd/J3sxZuqeQ1uaEzdIIcYuQTSNVw=
  # - secure: "VPzCcthpVEwaLabr3HQqDYF39WF9bQfV8zpZtFsKKuFljTI3ytohwgbaiWcCQKRdrQxKDaC700iOE/5/08tuSlaERVR3PWdamSDL+PKyjJ4lY6d2MEiH7OdeuZkKCpQOBIGJ+7yL/JF3gjrssj+kEyJXDnCa8TJImeNPSQYdvzRpWat6bQ/Wl7RrU8u8ReEyq54khVIQME2JSYCWPGsAifE1c7FMd/tF26I6brdDGH+5JoTHEvXsEIYf6y8mtszZmBisf4jMOV81d7PGQa3KjauyOP0AQDilRrHv17CNt8B4kZvmIlK4EcftiDBNekaV6YuUqJ8IK3U8vuXVYe2+jR3wCCDo0s8D/VWyJtcuIoyouINu0hEY6h0KJXOutZiUigPBkx4URbPuqT7McLIcyBaazJvQjTRHm5O4y95VRiLg5nxqeg7ZAzApPb2PrxbYFJbQK1pce335UnuixRmFy4yrj+q2sBGcB9vHS1oxL6uasTQG6MUFPhP+KW1AAC1qifXQ3lIKiVXiILfv/gn5D7hAKF3+9yJtTvOVOsee7P5fGy/cUaRkyegylZOyviY23MJaoVptpQuF7jR9E28SqSnZCSubi6bh/Q1vpyC0foXFOeq6DoHSCVh7oEv7GIkuC1FSoaZVwBCceKuxb8HhaSHa/toTE3YLLxlBTVrBN3A="
  # - secure: "fTcsWTqzMLn3L4ubBKZCwuolae2V+GkWIxe2ETkSBC3Ogiy8Lbl4KCPaukgEdiObN2iE33Ptjgkh/RumTMrI9IdZ25lleTPpVC8uI9wN1vGUGDVhVO7Y8nH6PCKM2OESkQtEJVfLST0W0yiwju9/kGCDNdAJSKDEFPpSj+BOSGNi/XLJFPL69lgOsDVB48KFcmbHIIXa9Ljvj9pSGm4Z1tIlPSW7UO8+sUhfkDvQGc28/ipodBxwe/Ldu5sZrXjO0Val9xLRCSUWfV8Y8OTQ70o0Xf5JrPir+XEGYOV9tTvbrO07KWk32FLnVuAUz42vgDT8e/suPjFJDD/N3quDPA5DqCoo/Agn2+7OocIiBC8KfzWC728rmE5VI68xVncGhbrKoO6ZP5ufd8wWVy908fxB0NltlzF7oCNcCiS/jhDoNd8Gx+jH1KlhhbqC+aY/rHSh57et4Lj6uQp42xkEZVNXRu4vPYArkIczwEEM/lxpdyVtntJF09g4ECoey8JnHcC4h8856NapbPE0JLEStO6o27uCFITa2Q2MQIqJESvG8Gsw6kA77yf0l64De70/V/f2YmqkBaEfybK7+8o+b9IGXJUz2OT8i7EJ1lUQghDf9DQZKkeR1rAc3a6oN3IJIHe5quVK2EYbSx0Gy+ReXzOS82XFuMB5og9Pv+c+tp0="
