services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from j0elwee/devops-trg -t j0elwee/devops-trg -t j0elwee/devops-trg:$TRAVIS_COMMIT --target production .
  - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from j0elwee/devops-trg:ci -t j0elwee/devops-trg:ci --target ci .
  - docker-compose -f docker-compose.test.yml build
script:
  - docker-compose -f docker-compose.test.yml up --exit-code-from tests
before_deploy:
  - echo $DOCKER_HUB_PASSWORD | docker login -u j0elwee --password-stdin
  - docker push j0elwee/devops-trg
  - docker push j0elwee/devops-trg:$TRAVIS_COMMIT
  - docker push j0elwee/devops-trg:ci
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo $HEROKU_API_KEY | docker login -u j0elwee --password-stdin registry.heroku.com
  - docker tag j0elwee/devops-trg registry.heroku.com/devops-trg/web
  - docker push registry.heroku.com/devops-trg/web
deploy:
  provider: script
  script: heroku container:release web -a devops-trg
  on: 
    branch: mod-9-db
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.28.2
  - secure: UwMUyLZN1g+zqo+7+xIftHXzpWSKUWhS2DZHQSMdPURlD/n9GMZvuJXJ7mzh1MV1KJi+acIPE7Ho3pLVdu1zTkJ47oN8dsnLzXih6yaqD768b51/u0v/G49+9nsjUBkQ5ds7ZvC9OyW1uYKU1aUfjL9X3ejcbmUbfXTMLGPFPbRS/4S3a9HmgzYjFCPPEMZvwppufojhZ72HirjYISRk0KjB+KWcmqShpsZvef+H4VEdGTsdiWjhq3SaTU1R7FF5kcg4j3hN5guZFwIYfJMVG8RouCvzGU2voAbBNImu5Dugwna0cZJPZVJvz88vTimMKal8E22EC3aNaduB9pNcF9lWYmSwL/aoXCGfXke9swXRtSV4Ma+cpZYFb+ju/Af2WoOybs9ygTH5L5aV7wg3P5XuB1AkCPbr1uQsmQbENvDqJNU8hhDmezYXhr4jLOtZ8DF37jtMDhUAeFhQpKZMcxaay5cvaupEUILI1QaFWSmcYgXWz0yonR0gooXZHfZYJZZ98nFqOGGsLgrz/M0DVN6EBBRqNXjKW8RtTzHXRDe2EuPu2r7UrLbE1upTAHwc9xtAWxVorTxkpZvFA9bml0HGjS8ak2yRfVxrDC/Xm5wGPsNBLkRh73h2H5UjOjEyRiumPOKM/JrEwysd/J3sxZuqeQ1uaEzdIIcYuQTSNVw=
  - secure: s0iHDCGnS/PtBxHi/s/+5rEho2ZhMs+KpV6zMEqSNBxFS58+1zq0xX7GHeOyEAfTouTFnHyy1edAqVfLdNozLYqf7XjIZUztmMEtrcKJcndH9YBDwLOFA0CfA5HEG9AoKcskIXT0eEvf9oZ8E1viWvrjvXiBu8FkvwXsEbzIY1GoImiMpHQGoQ/PdRTEhb7XIV06zZaltF3B2/r9boqAqQEsieXYgr3uJXssjdnh7eolsC7lTuMcK/O2KGWYmM4Tlfw5xD9D8Uvxr52OLwfIvitLAHjG59et2zeM4oTy2nAQso8PwzUFoC65C9g9lEWD2k7EadrrukKJrJjmylmWFrYTjSxPdsk2ye0Uv07Rtv/aYv5Vnqf5c0HF5K+w7feWXbK5Mw7lSbRY9gzAThTyNe4prjfDJcqIV5bQXXv8E8IvA3KjNqWdMNTE33832a/Uaev+uYqjgSPFl9xd6S34KxOQJG1kNNVl9eZDi9Pxi3WYYJZIS2cosidgFQTNxzQuPTU+yj7agnbhDw5taB6lDUo3NWJconerLyr9R0TOwb+dvxb2vOGlYqLqnYDkbmQgzLmqiZAEb/yDbSb689y9G4YeU7T9pAvbZHiKdhN5S9gt2IU++ARpri4m5uYljp7pSZawKPgX+e5/Tc6SrLW9BYfexYIQnmR2UFvSXBDUdy0=
  - secure: MtQjfIbBQ95rxeqiAbqXo/YEZsTx1ghiSPX73CDzmdSuZIGJM5Cq3zWvO0Ich8rgTdLMZtt1fs28om2R+NMyKxbTZcshOBRgWpXwvCIKTyVh98uwuCbSsbqfz/VTOzamUA6YQARX5UFFw8hbwAxqESRcYK3M3bOEO94LjE22YkkDSp0j3FV9QbcPBKd/CZaXzP/YFEPlI4pMf8jpKwMCLLUmYfk2093SXVGGYQE8Zz3zuVkUIrTk2QvLNdpPPWeuUoAR0wssp0x2TqnWUNuwzLSs6qYQmDlh5+RZt0iWTFLaa98I08c0DoeGRBCw3OdUgH9aaV4BIGI8yDFREknpyrJIwuvLG6FR8HH+PXQIpcjn4bg9dnE+nWWmZn7KVGjTvlKr0tfZV+1D0iFzhMTStC8uKF8zIBw5kOE0swcAyK2cMFcTXNHG82h1nIwjRPFM0O/ydHjwdlLGqZKZCAumo740fIdcGBtluxRcdDfw8M9+vysoI/eZEls0U9wu1x0eQ0UlBKVhRSxophHklgI8rnzVa/AtNScIKIH3leeM/KThe4YaFIgADNLY6hEseU1dFhw86RcqYdGdd9GarwMoJpBI5MEdooS6TJG3FkqRp/zd4DK2Wyd60KNc9SsGfpyFtvAOLAMaJdbKTgv76aslK9h2bCrPGuDEwJMWe/3fcVA=
