version: "3.8"
services:
  tests:
    build:
      context: .
      target: ci
    environment:
      - "MONGO_TEST_BASE_URI=mongodb://db:27017"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
