version: "3.8"
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
      target: test_watch
    env_file: .env
    volumes:
      - .:/app
